// Code generated by gen/gen.go from gen/reqrep.h. DO NOT EDIT.

package reqrep

import "unsafe"

const (
	layoutHdrArenaUsed = 204
	layoutHdrArenaWpos = 200
	layoutHdrMagic = 0
	layoutHdrMode = 8
	layoutHdrMutex = 192
	layoutHdrMutexWaiters = 196
	layoutHdrRecvFutex = 76
	layoutHdrRecvWaiters = 72
	layoutHdrReqArenaCap = 32
	layoutHdrReqArenaOff = 28
	layoutHdrReqCap = 12
	layoutHdrReqHead = 64
	layoutHdrReqSlotsOff = 24
	layoutHdrReqTail = 128
	layoutHdrRespDataMax = 40
	layoutHdrRespHint = 208
	layoutHdrRespOff = 44
	layoutHdrRespSlots = 36
	layoutHdrRespStride = 48
	layoutHdrSendFutex = 140
	layoutHdrSendWaiters = 136
	layoutHdrSlotFutex = 216
	layoutHdrSlotWaiters = 220
	layoutHdrStatRecoveries = 212
	layoutHdrStatRecvEmpty = 248
	layoutHdrStatReplies = 232
	layoutHdrStatRequests = 224
	layoutHdrStatSendFull = 240
	layoutHdrTotalSize = 16
	layoutHdrVersion = 4
	layoutLockTimeoutSec = 2
	layoutMagic = 0x52525331
	layoutModeInt = 1
	layoutModeStr = 0
	layoutMutexPidMask = 0x7FFFFFFF
	layoutMutexWriterBit = 0x80000000
	layoutReqArenaOff = 0
	layoutReqArenaSkip = 8
	layoutReqPackedLen = 4
	layoutReqRespGen = 16
	layoutReqRespSlot = 12
	layoutRespAcquired = 1
	layoutRespDataStart = 32
	layoutRespFlags = 16
	layoutRespFree = 0
	layoutRespGeneration = 20
	layoutRespLen = 12
	layoutRespOwnerPid = 8
	layoutRespReady = 2
	layoutRespState = 0
	layoutRespWaiters = 4
	layoutSizeofHeader = 256
	layoutSizeofReqSlot = 24
	layoutSizeofRespSlot = 32
	layoutSpinLimit = 32
	layoutStrLenMask = 0x7FFFFFFF
	layoutUtf8Flag = 0x80000000
	layoutVersion = 1
)

// hdrField32 and hdrField64 are inlined by the compiler; no bounds check.
func hdrField32(base unsafe.Pointer, off uintptr) *uint32 {
	return (*uint32)(unsafe.Pointer(uintptr(base) + off))
}

func hdrField64(base unsafe.Pointer, off uintptr) *uint64 {
	return (*uint64)(unsafe.Pointer(uintptr(base) + off))
}
